Models/ApiHelper.cs
using System.Threading.Tasks;
using RestSharp;

namespace deliver_me_deliveries.Models
{
  class ApiHelper
  {
    public static async Task<string> GetAll(string apiKey)
    {
      RestClient client = new RestClient("https://eatstreet.com/publicapi/v1");
      RestRequest request = new RestRequest($"restaurant/search?method=delivery&street-address=Seattle", Method.GET);
      request.AddHeader("X-Access-Token", apiKey);

      var response = await client.ExecuteTaskAsync(request);
      return response.Content;
    }
        
    public static async Task<string> Search(string addressSearch, string extraTerm = "")
    {
      //set up RestSharp api variables
      RestClient baseUrl = new RestClient("https://eatstreet.com/publicapi/v1/");
      RestRequest request = new RestRequest($"restaurant/search?", Method.GET);

      //additional parameters to add to the request
      request.AddHeader("X-Access-Token", EnvironmentVariables.ApiKey); //authentication
      if(extraTerm != ""){ request.AddQueryParameter("search", extraTerm); }  //extra search term
      request.AddQueryParameter("method", "delivery"); //delivery/pickup/both
      request.AddQueryParameter("street-address", addressSearch); //street address
    
      var response = await baseUrl.ExecuteTaskAsync(request);
      return response.Content;
    }

    public static async Task<string> GetDetails(string apiKey)
    {
        RestClient client = new RestClient("https://eatstreet.com/publicapi/v1/");
        RestRequest request = new RestRequest($"restaurant/{apiKey}", Method.GET);
        request.AddHeader("X-Access-Token", EnvironmentVariables.ApiKey);

        var response = await client.ExecuteTaskAsync(request);
        return response.Content;
    }
  }
}

Models/ApplicationUser.cs
using Microsoft.AspNetCore.Identity;

namespace deliver_me_deliveries.Models
{
    public class ApplicationUser : IdentityUser
    {

    }
}

Models/EnvironmentalVariables.cs
namespace deliver_me_deliveries.Models
{
    public static class EnvironmentVariables
    {
        public static string ApiKey = "P5LG4JN6VERBYZJRTPHAMLF75I======";
  }
}

Models/Restaurant.cs
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace deliver_me_deliveries.Models
{
  public class Restaurant
  {
    public int Id { get; set; }
    public string Name { get;set; }
    public string StreetAddress { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Zip { get; set; }
    public List<string> FoodTypes { get; set; }
    public string Phone { get; set; }
    public string ApiKey { get; set; }
    public string LogoUrl { get; set; }
    
    public static List<Restaurant> GetRestaurants()
    {
      var apiCallTask = ApiHelper.GetAll(EnvironmentVariables.ApiKey);
      var result = apiCallTask.Result;
      JObject jsonResponse = JsonConvert.DeserializeObject<JObject>(result);
      List<Restaurant> restaurantList = JsonConvert.DeserializeObject<List<Restaurant>>(jsonResponse["restaurants"].ToString());
      return restaurantList;
    }

    public static List<Restaurant> Search(string addressSearch, string extraTerm = "")
    {     
      var apiCallTask = ApiHelper.Search(addressSearch, extraTerm);
      var result = apiCallTask.Result;
      JObject jsonResponse = JsonConvert.DeserializeObject<JObject>(result);
      List<Restaurant> restaurantList = JsonConvert.DeserializeObject<List<Restaurant>>(jsonResponse["restaurants"].ToString());
      return restaurantList;
    }

    public static Restaurant GetDetail(string ApiKey)
    {     
      var apiCallTask = ApiHelper.GetDetails(ApiKey);
      var result = apiCallTask.Result;
      JObject jsonResponse = JsonConvert.DeserializeObject<JObject>(result);
      Restaurant restaurant = JsonConvert.DeserializeObject<Restaurant>(jsonResponse["restaurant"].ToString());
      return restaurant;
    }
  }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PagedList;
using PagedList.Mvc;

namespace deliver_me_deliveries.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Controllers/RestaurantController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using deliver_me_deliveries.Models;
using Microsoft.AspNetCore.Authorization;
using System;

namespace deliver_me_deliveries.Controllers
{

    // [Route("api/[controller]")]
    // [ApiController]
    public class RestaurantController : Controller
    {

        // GET api/Restaurant
       
        public IActionResult Index()
        {
            var allRestaurants = Restaurant.GetRestaurants();
            return View(allRestaurants);
        }

        [HttpGet]
        public IActionResult GetAll()
        {
          var allRestaurants = Restaurant.GetRestaurants();
          return View("Index", allRestaurants);
        }
    }
}

Controllers/RestaurantsController.cs
using Microsoft.AspNetCore.Mvc;
using deliver_me_deliveries.Models;

namespace deliver_me_deliveries.Controllers
{
    public class RestaurantsController : Controller
    {  
        public IActionResult Index()
        {
           
           var allRestaurants = Restaurant.GetRestaurants();
            return View(allRestaurants);
        }    

        [HttpGet]
        
        public IActionResult GetAll()
        {     
            var allRestaurants = Restaurant.GetRestaurants();
            return View("Index", allRestaurants);
        }

        public IActionResult Search(string addressSearch, string extraTerm = "")
        {        
            var searchResults = Restaurant.Search(addressSearch, extraTerm);
            return View("Search", searchResults);
        }

        [HttpGet("{ApiKey}")]
        public IActionResult Details(string ApiKey)
        {           
          var restaurant = Restaurant.GetDetail(ApiKey);            
          return View(restaurant);
        }        
    }
}

Controllers/RetaurantController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using deliver_me_deliveries.Models;
using Microsoft.AspNetCore.Authorization;
using System;
using deliver_me_deliveries.Models;

namespace deliver_me_deliveries.Controller
{

    [Route("api/[controller]")]
    [ApiController]
    public class AnimalsController : ControllerBase
    {


        // GET api/animals
        public IActionResult Index()
        {
            var allRestaurants = Restaurant.GetAll();
            return View(allRestaurants);
        }

        [HttpGet]
        public IActionResult GetAll()
        {
          var allRestaurants = Restaurant.GetAll();
          return View("Index", allRestaurants);
        }
    }
}

Views/Home/Index.cshtml
@{
    Layout = "_Layout";
}

@model deliver_me_deliveries.Models.Restaurant;
<div class="parent">
 <div class="caropictures">
 <div id="carouselExampleControls" class="carousel slide"   data-ride="carousel">
 <div class="carousel-inner">
     <div class="carousel-item active">
     <img class="d-block w-100" src="img/slide1.jpg" alt="First slide">
     </div>
     <div class="carousel-item">
     <img class="d-block w-100" src="img/slide2.webp" alt="Second slide">
     </div>
     <div class="carousel-item">
     <img class="d-block w-100" src="img/slide3.jpg"  alt="Third slide">
     </div>
 </div>
<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
</a>
<a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
</a>
</div>
<div class="bio">
<h5>About:</h5>
<p>DeliverMe! Deliveries™ was created as a platform to help customers access available places for delivery from home. It's our goal to make sure that people are able to still enjoy dishes from some of their favorite restaurants from the safety and comfort of their home. Established 2020.</p>
</div>
</div>
 <div class="box">
    <div id="intro">
     <img src="~/img/logo.png" alt="logo"width="30%" >
    </div>
<form action="/Restaurants/Search" method="post">

    <div class="searchBar">
     <label for="addressSearch">Street Address</label>
     <label for="extraTerm">Search Term</label>
    </div>
    <div class="searchBar">
     <input id="addressSearch" name="addressSearch" type="text">
     <input id="extraTerm" name="extraTerm" type="text">     
    </div>
   
   <div class="center">
     <button id="search" type="submit">Search</button>
</form>
  <button id="all">@Html.ActionLink("See all results", "Index", "Restaurants")</button>
  </div>
</div>
 </div>
</div>
  
    

Views/Restaurants/Details.cshtml
@{
    Layout = "_Layout";
}

<div id="parent3">
  <div class="box4">
    <div class="logo-margin2">
      <img src="@Model.LogoUrl" width="150px">
    </div>
    <br>
    <h3><strong><em>@Model.Name</em></strong></h3>
    <h5>Address:</h5>
      <p>@Model.StreetAddress @Model.City, @Model.State @Model.Zip</p>      
    <h5>Contact:</h5>
      <p>@Model.Phone</p>
    </div>
    <br>
  </div>
</div>

Views/Restaurants/Index.cshtml
<!DOCTYPE html>
<html>
  <head>
    <style>
      #map {
        width: 100%;
        height: 400px;
        background-color: grey;
        position: sticky;
      }
    </style>
     <link rel="stylesheet" type="text/css" href="~/css/style.css" />
  </head>
  <body>
   
    @using deliver_me_deliveries.Models;
    <div class="parent3">
      <div id="map"></div>

 <script>
// Initialize and add the map
function initMap() {
  // The location of Uluru
  var seattle = {lat: 47.608940, lng: -122.340141, address:"1521 1st Ave, Seattle, WA"}
  // The map, centered at Uluru
  var map = new google.maps.Map(
      document.getElementById('map'), {zoom: 11, center: seattle});
  // The marker, positioned at Uluru
  var marker = new google.maps.Marker({position: seattle, map: map});
}
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD-CbiljbNW94CCtFsBF5xQTMiv8ncY_KY&callback=initMap">
    </script>
    


      <div class="box2">
    @foreach (Restaurant restaurant in Model)
    {
          <div class="logo-margin">
          <a href="/Restaurants/Details/@(restaurant.ApiKey)"><img src="@restaurant.LogoUrl" width="90px" height="90px"></a>
          </div>
          <div class="info-margin">
            <h3><strong><em>@restaurant.Name</em></strong></h3>
            <h5>Address:</h5>
              <p>@restaurant.StreetAddress @restaurant.City, @restaurant.State @restaurant.Zip</p>
              <p>@Html.ActionLink($"{restaurant.Name}", "Details", new { ApiKey = restaurant.ApiKey })</p>
          </div>
          <hr>
        }
        
        </div>
    </div>
  </body>
</html>

Views/Restaurants/Search.cshtml
<!DOCTYPE html>
<html>
  <head>
     <link rel="stylesheet" type="text/css" href="~/css/style.css" />
  </head>
  <body>
    @using deliver_me_deliveries.Models;

    <div id="parent2">
    <div class="box3">
    @foreach (Restaurant restaurant in Model)
    {
       <div class="searchInfo">
       <div class="logo-margin2">
         <img src="@restaurant.LogoUrl" width="150px">
          </div>
          <br>
        <h3><strong><em>@restaurant.Name</em></strong></h3>
        <h5>Address:</h5>
        <p>@restaurant.StreetAddress @restaurant.City, @restaurant.State @restaurant.Zip</p>
      
        <h5>Contact:</h5>
        <p>@restaurant.Phone</p>
       </div>
        <br>
    }
    </div>
    </div>
  </body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]  DeliverMe! Deliveries™</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    
    
    <link rel="stylesheet" href="~/css/style.css" />
   
</head>
<body>
    <header class="headerTop">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="img/logo.png" width="60px"> </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - DeliverMe! Deliveries™ - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>